### ISSUE TITLE
Document "Unknown sources" requirement

### ISSUE THREAD

**Issue by PhilippMundhenk** [martoreto/aauto-sdk#4]
Hi,

first of all: Awesome project! Great work! Love to be able to use this!

I manage to port a car-related app I was writing to AAuto with this by basing of aauto-sdk-demo. However, it only seems to work when using the simulated headunit supplied with the Android SDK. When attaching to my car, it simply does not show up in the OEM menu.
Although it should only be relevant to vendor channel, I tried changing the package name to one that is allowed by my infotainment system, still no luck.

Any ideas what could be the reason why it works in developer mode with the simulator but refuses to show up in the car?

Thank you!

**Comment by jilleb** [comment]
Did you enable apps from unknown sources in the developer settings?

**Comment by PhilippMundhenk** [comment]
Isn't this in security settings? 
Yes, is currently enabled.

But I am running the Debug version of the app downloaded via ADB.

**Comment by jilleb** [comment]
No, for AA this setting is not in security settings but in Developer Settings in AA.

**Comment by PhilippMundhenk** [comment]
I see! I did not discover this setting yet. I will activate it and see if it shows up then...
Be right back.. ;)

**Comment by PhilippMundhenk** [comment]
Ha!! It works! Excellent!
Thank you for your help!

@martoreto: Might make sense to put this into the readme. I admit I haven't read up too deeply on the topic and just started trying out, but I haven't seen this option anywhere. Might help others, too.

**Comment by martoreto** [comment]
That's definitely a good idea to have this documented.
What about creating a simple pull request?

**Comment by PhilippMundhenk** [comment]
Good idea! Done.

**Comment by martoreto** [comment]
Thanks!
